version: '3.2'
services:
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3333
    volumes:
      - .:/usr/src/pesquisa
    ports:
      - "3333:3333"
    command: sh -c "npm run build && npm run start"
    working_dir: /usr/src/pesquisa

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs

